//this id is to look for language.xml

#define MENU_FILE 1
#define MENU_WINDOW 2
#define MENU_CLOSE_ALL 3
#define MENU_OPEN_ALL 4
#define MENU_ACTOR 5
#define MENU_HIERARCHY 6
#define MENU_GAME_VIEW 7
#define MENU_SCENE_VIEW 8
#define MENU_INSPECTOR 9
#define MENU_TOOLBAR 10
#define MENU_CONSOLE 38
#define MENU_ASSET_BROWSER 11
#define MENU_MATERIAL_EDITOR 12
#define MENU_CREATE_EMPTY 13
#define MENU_PRIMITIVE 14
#define MENU_CUBE 15
#define MENU_SPHERE 16

#define MENU_LANGUAGE 17
#define MENU_LANGUAGE_ZH_CN 18
#define MENU_LANGUAGE_EN_US 19
#define MENU_LANGUAGE_VI_VN 20
#define MENU_LANGUAGE_ZH_TW 21

#define MATERIAL_TEXT 22
#define SHADER_TEXT 23

#define EMPTY_TEXT 24

#define MATERIAL_EDITOR_SAVE 25
#define MATERIAL_EDITOR_RELOAD 26
#define MATERIAL_EDITOR_PREVIEW 27
#define MATERIAL_EDITOR_RESET 28

#define MATERIAL_SETTING 29
#define SHADER_SETTING 30

#define DIRECTIONLIGHT_TEXT 31
#define AMBIENTLIGHT_TEXT 32
#define MainCAMERA_TEXT 33

#define POSITION_TEXT 34
#define ROTATION_TEXT 35
#define SCALE_TEXT 36

#define CLEAR_TEXT 37

#define FIELD_OF_VIEW_TEXT 39
#define ORTHOGRAPHICS_SIZE 40

#define NEAR_PANEL 41
#define FAR_PANEL 42

#define CLEAR_COLOR 43

#define PROJECTION_MODE 44





